"use client";
import Image from "next/image";
import { FormEvent, useState } from "react";

const API_URL = process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:3339";
const modalities = [['SEGUIR_LINHA', 'Seguir Linha']] as const;
const makeCompetitor = () => ({ name: "", inepCode: "", birthDate: "", city: "", email: "", phone: "", document: null as File | null });
type Competitor = ReturnType<typeof makeCompetitor>;
type Notice = { type: "success" | "error"; text: string } | null;
const steps = ["Etapa", "Instituição", "Equipe", "Competidores", "Revisão"];

function Field({ label, required = false, children, hint }: { label: string; required?: boolean; children: React.ReactNode; hint?: string }) {
  return <label className="field"><span>{label}{required && <b aria-hidden="true"> *</b>}</span>{children}{hint && <small>{hint}</small>}</label>;
}
function Input(props: React.InputHTMLAttributes<HTMLInputElement>) { return <input {...props} className={`input ${props.className ?? ""}`} />; }
function Select(props: React.SelectHTMLAttributes<HTMLSelectElement>) { return <select {...props} className={`input ${props.className ?? ""}`} />; }

export default function Home() {
  const [step, setStep] = useState(1); const [loading, setLoading] = useState(false); const [notice, setNotice] = useState<Notice>(null);
  const [stage, setStage] = useState({ name: "TJR — Paraíba", state: "PB", venue: "", competitionDate: "" });
  const [institution, setInstitution] = useState({ name: "", cnpj: "", inepCode: "", city: "", instagramUrl: "", isPatos: false });
  const [responsible, setResponsible] = useState({ fullName: "", document: "", inepCode: "", institutionName: "", email: "", phone: "" });
  const [team, setTeam] = useState({ name: "", state: "PB", city: "", modalities: ["SEGUIR_LINHA"] as string[], isGarage: false, marketingCompetitorIndex: null as number | null });
  const [competitors, setCompetitors] = useState<Competitor[]>([makeCompetitor(), makeCompetitor(), makeCompetitor()]);
  const [accepted, setAccepted] = useState(false);
  const [imageUseConsent, setImageUseConsent] = useState(false);

  const updateCompetitor = (index: number, key: keyof Competitor, value: string | File | null) => setCompetitors((current) => current.map((member, i) => i === index ? { ...member, [key]: value } : member));
  const toggleModality = (value: string) => setTeam((current) => ({ ...current, modalities: current.modalities.includes(value) ? current.modalities.filter((item) => item !== value) : [...current.modalities, value] }));
  const validateStep = () => {
    if (step === 1 && Object.values(stage).some((value) => !value)) return "Preencha os dados da etapa.";
    if (step === 1 && !imageUseConsent) return "Autorize o uso de imagem para continuar.";
    if (step === 2 && (!institution.name || !institution.cnpj || !institution.city || !institution.isPatos || institution.city.trim().normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase() !== "patos")) return "A instituição deve ser de Patos-PB, com nome e CNPJ.";
    if (step === 2 && (!responsible.fullName || !responsible.document || !responsible.email || !responsible.phone)) return "Preencha todos os dados obrigatórios do técnico.";
    if (step === 3 && (!team.name || !team.state || !team.city || team.modalities.length === 0)) return "Complete os dados da equipe, nível e modalidades.";
    if (step === 4 && competitors.some((member) => !member.name || !member.birthDate || !member.city || !member.email || !member.phone || !member.document)) return "Preencha todos os competidores e envie uma identidade para cada um.";
    return null;
  };
  const next = () => { const error = validateStep(); if (error) { setNotice({ type: "error", text: error }); return; } setNotice(null); setStep((current) => Math.min(5, current + 1)); };
  const submit = async (event: FormEvent) => {
    event.preventDefault(); const error = validateStep(); if (error) { setNotice({ type: "error", text: error }); return; } if (!accepted) { setNotice({ type: "error", text: "Aceite a declaração para concluir o cadastro." }); return; }
    setLoading(true); setNotice(null);
    const payload = { stage, institution, responsible, team, competitors: competitors.map(({ name, inepCode, birthDate, city, email, phone }) => ({ name, inepCode, birthDate, city, email, phone })), acceptedDeclaration: accepted, imageUseConsent };
    const formData = new FormData(); formData.append("data", JSON.stringify(payload)); competitors.forEach((member) => { if (member.document) formData.append("documents", member.document); });
    try { const response = await fetch(`${API_URL}/registrations`, { method: "POST", body: formData }); const result = await response.json(); if (!response.ok || !result.success) throw new Error(result.error || "Não foi possível concluir o cadastro."); setNotice({ type: "success", text: "Cadastro realizado com sucesso. As identidades foram recebidas." }); }
    catch (submitError) { setNotice({ type: "error", text: submitError instanceof Error ? submitError.message : "Erro inesperado." }); } finally { setLoading(false); }
  };
  return <main className="site-shell"><a className="skip-link" href="#cadastro">Ir para o cadastro</a><header className="topbar"><div className="brand"><Image src="/citi-logo.png" alt="CiTI-DE" width={48} height={48} priority /><div><strong>CiTI<span>-DE</span></strong><small>Robótica · Patos - PB</small></div></div><div className="topbar-note">Cadastro oficial<br /><b>Torneio Juvenil de Robótica</b></div></header>
    <section className="hero"><div className="hero-orb" aria-hidden="true" /><div className="hero-content"><p className="eyebrow">Ciência · Tecnologia · Inovação</p><h1>Inscrição de equipes<br /><em>de robótica</em></h1><p className="hero-copy">Cadastre sua instituição, técnico e equipe para participar das modalidades do TJR.</p><div className="hero-pills"><span>3 a 4 competidores</span><span>Identidade obrigatória</span><span>Até 19 anos</span></div></div></section>
    <section id="cadastro" className="form-wrap"><div className="progress" aria-label="Progresso do cadastro">{steps.map((label, index) => <div key={label} className={`progress-item ${step === index + 1 ? "active" : ""} ${step > index + 1 ? "done" : ""}`}><span>{index + 1}</span><small>{label}</small></div>)}</div>
      <form onSubmit={submit} className="card form-card"><div className="card-heading"><div><p className="eyebrow blue">Cadastro TJR</p><h2>{steps[step - 1]}</h2></div><span className="step-count">{step}/5</span></div>
        {step === 1 && <fieldset><legend>Onde e quando será a competição?</legend><div className="grid two"><Field label="Nome da etapa" required><Input value={stage.name} onChange={(e) => setStage({ ...stage, name: e.target.value })} required /></Field><Field label="Estado" required><Input value={stage.state} maxLength={2} onChange={(e) => setStage({ ...stage, state: e.target.value.toUpperCase() })} required /></Field><Field label="Local da competição" required><Input value={stage.venue} onChange={(e) => setStage({ ...stage, venue: e.target.value })} required /></Field><Field label="Data da competição" required><Input type="date" value={stage.competitionDate} onChange={(e) => setStage({ ...stage, competitionDate: e.target.value })} required /></Field></div><label className="check-row image-consent"><Input type="checkbox" checked={imageUseConsent} onChange={(e) => setImageUseConsent(e.target.checked)} /><span><b>Autorizo o uso de imagem</b><small>Permito o uso de fotos e vídeos dos participantes para divulgação institucional do torneio.</small></span></label></fieldset>}
        {step === 2 && <div className="stack"><fieldset><legend>Instituição / escola</legend><p className="section-hint">A instituição deve estar localizada em Patos-PB. Sem código INEP, a equipe será registrada como equipe de garagem.</p><div className="grid two"><Field label="Nome da instituição"><Input value={institution.name} onChange={(e) => setInstitution({ ...institution, name: e.target.value })} /></Field><Field label="CNPJ"><Input value={institution.cnpj} onChange={(e) => setInstitution({ ...institution, cnpj: e.target.value })} placeholder="00.000.000/0000-00" /></Field><Field label="Código INEP"><Input value={institution.inepCode} onChange={(e) => setInstitution({ ...institution, inepCode: e.target.value })} /></Field><Field label="Cidade"><Input value={institution.city} onChange={(e) => setInstitution({ ...institution, city: e.target.value })} /></Field><Field label="Instagram da instituição"><Input type="url" value={institution.instagramUrl} onChange={(e) => setInstitution({ ...institution, instagramUrl: e.target.value })} placeholder="https://instagram.com/..." /></Field></div><label className="check-row"><Input type="checkbox" checked={institution.isPatos} onChange={(e) => setInstitution({ ...institution, isPatos: e.target.checked })} /> <span>A instituição é de Patos</span></label></fieldset><fieldset><legend>Técnico / professor responsável</legend><div className="grid two"><Field label="Nome completo" required><Input value={responsible.fullName} onChange={(e) => setResponsible({ ...responsible, fullName: e.target.value })} required /></Field><Field label="RG ou CPF" required><Input value={responsible.document} onChange={(e) => setResponsible({ ...responsible, document: e.target.value })} required /></Field><Field label="Código INEP do técnico"><Input value={responsible.inepCode} onChange={(e) => setResponsible({ ...responsible, inepCode: e.target.value })} /></Field><Field label="Instituição de que faz parte"><Input value={responsible.institutionName} onChange={(e) => setResponsible({ ...responsible, institutionName: e.target.value })} /></Field><Field label="E-mail" required><Input type="email" value={responsible.email} onChange={(e) => setResponsible({ ...responsible, email: e.target.value })} required /></Field><Field label="Telefone" required><Input type="tel" value={responsible.phone} onChange={(e) => setResponsible({ ...responsible, phone: e.target.value })} required /></Field></div></fieldset></div>}
        {step === 3 && <div className="stack"><fieldset><legend>Dados da equipe</legend><div className="grid two"><Field label="Nome da equipe" required><Input value={team.name} onChange={(e) => setTeam({ ...team, name: e.target.value })} required /></Field><Field label="Quantidade de integrantes"><Select value={competitors.length} onChange={(e) => { const count = Number(e.target.value); setCompetitors((current) => Array.from({ length: count }, (_, i) => current[i] ?? makeCompetitor())); }}><option value={3}>3 integrantes</option><option value={4}>4 integrantes</option></Select></Field><Field label="Estado" required><Input value={team.state} maxLength={2} onChange={(e) => setTeam({ ...team, state: e.target.value.toUpperCase() })} required /></Field><Field label="Cidade" required><Input value={team.city} onChange={(e) => setTeam({ ...team, city: e.target.value })} required /></Field></div><label className="check-row garage"><Input type="checkbox" checked={team.isGarage} onChange={(e) => setTeam({ ...team, isGarage: e.target.checked })} /><span><b>Equipe de garagem</b><small>Marque quando não houver código INEP da instituição.</small></span></label></fieldset><fieldset><legend>Modalidades</legend><p className="section-hint">Selecione uma ou mais modalidades da equipe.</p><div className="modalities">{modalities.map(([value, label]) => <label key={value} className="modality"><Input type="checkbox" checked={team.modalities.includes(value)} onChange={() => toggleModality(value)} /><span>{label}</span></label>)}</div></fieldset></div>}
        {step === 4 && <fieldset><legend>Competidores</legend><p className="section-hint">Entre 3 e 4 alunos. A identidade é obrigatória para todos os competidores.</p><div className="competitor-list">{competitors.map((member, index) => <article className="competitor" key={index}><div className="competitor-title"><span>{String(index + 1).padStart(2, "0")}</span><h3>Competidor {index + 1}</h3><label className="marketing"><Input type="radio" name="marketing" checked={team.marketingCompetitorIndex === index} onChange={() => setTeam({ ...team, marketingCompetitorIndex: index })} /> Responsável pelo marketing</label></div><div className="grid two"><Field label="Nome completo" required><Input value={member.name} onChange={(e) => updateCompetitor(index, "name", e.target.value)} required /></Field><Field label="Código INEP"><Input value={member.inepCode} onChange={(e) => updateCompetitor(index, "inepCode", e.target.value)} /></Field><Field label="Data de nascimento" required><Input type="date" value={member.birthDate} onChange={(e) => updateCompetitor(index, "birthDate", e.target.value)} required /></Field><Field label="Cidade onde reside" required><Input value={member.city} onChange={(e) => updateCompetitor(index, "city", e.target.value)} required /></Field><Field label="E-mail" required><Input type="email" value={member.email} onChange={(e) => updateCompetitor(index, "email", e.target.value)} required /></Field><Field label="Telefone" required><Input type="tel" value={member.phone} onChange={(e) => updateCompetitor(index, "phone", e.target.value)} required /></Field><Field label="Identidade (PDF, JPG ou PNG)" required><Input type="file" accept="application/pdf,image/jpeg,image/png" onChange={(e) => updateCompetitor(index, "document", e.target.files?.[0] ?? null)} required /></Field></div></article>)}</div></fieldset>}
        {step === 5 && <fieldset><legend>Revise e confirme</legend><div className="review"><div><span>Instituição</span><b>{institution.name || (team.isGarage ? "Equipe de garagem" : "Não informada")}</b></div><div><span>Equipe</span><b>{team.name} · {competitors.length} competidores</b></div><div><span>Modalidade</span><b>Seguir Linha</b></div><div><span>Técnico responsável</span><b>{responsible.fullName}</b></div></div><label className="declaration"><Input type="checkbox" checked={accepted} onChange={(e) => setAccepted(e.target.checked)} /><span>Declaro que os dados informados são verdadeiros, que os competidores pertencem à equipe inscrita e autorizo o tratamento das informações para organização do torneio.</span></label></fieldset>}
        {notice && <div className={`notice ${notice.type}`} role={notice.type === "error" ? "alert" : "status"}>{notice.text}</div>}
        <div className="form-actions"><button type="button" className="button secondary" onClick={() => { setNotice(null); setStep((current) => Math.max(1, current - 1)); }} disabled={step === 1}>Voltar</button>{step < 5 ? <button type="button" className="button primary" onClick={next}>Continuar <span aria-hidden="true">→</span></button> : <button type="submit" className="button primary" disabled={loading}>{loading ? "Enviando…" : "Finalizar cadastro"}</button>}</div>
      </form>
    </section><footer className="footer"><span>CiTI-DE · Secretaria de Ciência, Tecnologia, Inovação e Desenvolvimento Econômico</span><span>Patos · Paraíba</span></footer></main>;
}
